"""
Web Models Configuration - Provider definitions and constants
"""

from typing import Dict, Any

WEB_PROVIDERS_CONFIG: Dict[str, Dict[str, Any]] = {
    "claude-web": {
        "name": "Claude Web",
        "base_url": "https://claude.ai",
        "default_model": "claude-sonnet-4-6",
        "client_module": "clients.claude_web",
        "client_class": "ClaudeWebClient",
        "context_window": 200000,
        "max_tokens": 8192,
        "cost": {"input": 0, "output": 0, "cacheRead": 0, "cacheWrite": 0},
        "description": "Claude through claude.ai (browser session)",
        "auth_url": "https://claude.ai/",
    },
    "chatgpt-web": {
        "name": "ChatGPT Web",
        "base_url": "https://chatgpt.com",
        "default_model": "gpt-4",
        "context_window": 128000,
        "max_tokens": 4096,
        "cost": {"input": 0, "output": 0, "cacheRead": 0, "cacheWrite": 0},
        "description": "ChatGPT through chatgpt.com (browser session)",
        "auth_url": "https://chatgpt.com/",
    },
    "deepseek-web": {
        "name": "DeepSeek Web",
        "base_url": "https://chat.deepseek.com",
        "default_model": "deepseek-chat",
        "context_window": 64000,
        "max_tokens": 8192,
        "cost": {"input": 0, "output": 0, "cacheRead": 0, "cacheWrite": 0},
        "description": "DeepSeek through chat.deepseek.com (browser session)",
        "auth_url": "https://chat.deepseek.com/",
    },
    "doubao-web": {
        "name": "Doubao Web",
        "base_url": "https://www.doubao.com",
        "default_model": "doubao-seed-2.0",
        "context_window": 64000,
        "max_tokens": 8192,
        "cost": {"input": 0, "output": 0, "cacheRead": 0, "cacheWrite": 0},
        "description": "Doubao through www.doubao.com (browser session)",
        "auth_url": "https://www.doubao.com/",
    },
    "gemini-web": {
        "name": "Gemini Web",
        "base_url": "https://gemini.google.com",
        "default_model": "gemini-pro",
        "context_window": 32000,
        "max_tokens": 8192,
        "cost": {"input": 0, "output": 0, "cacheRead": 0, "cacheWrite": 0},
        "description": "Gemini through gemini.google.com (browser session)",
        "auth_url": "https://gemini.google.com/",
    },
    "glm-web": {
        "name": "GLM Web",
        "base_url": "https://chatglm.cn",
        "default_model": "glm-4-plus",
        "context_window": 32000,
        "max_tokens": 8192,
        "cost": {"input": 0, "output": 0, "cacheRead": 0, "cacheWrite": 0},
        "description": "GLM through chatglm.cn (browser session)",
        "auth_url": "https://chatglm.cn/",
    },
    "grok-web": {
        "name": "Grok Web",
        "base_url": "https://grok.com",
        "default_model": "grok-2",
        "context_window": 32000,
        "max_tokens": 4096,
        "cost": {"input": 0, "output": 0, "cacheRead": 0, "cacheWrite": 0},
        "description": "Grok through grok.com (browser session)",
        "auth_url": "https://grok.com/",
    },
    "kimi-web": {
        "name": "Kimi Web",
        "base_url": "https://www.kimi.com",
        "default_model": "moonshot-v1-32k",
        "context_window": 32000,
        "max_tokens": 4096,
        "cost": {"input": 0, "output": 0, "cacheRead": 0, "cacheWrite": 0},
        "description": "Kimi (Moonshot) through www.kimi.com (browser session)",
        "auth_url": "https://www.kimi.com/",
    },
    "qwen-web": {
        "name": "Qwen Web",
        "base_url": "https://chat.qwen.ai",
        "default_model": "qwen-max",
        "context_window": 32000,
        "max_tokens": 8192,
        "cost": {"input": 0, "output": 0, "cacheRead": 0, "cacheWrite": 0},
        "description": "Qwen (Tongyi Qianwen) through chat.qwen.ai (browser session)",
        "auth_url": "https://chat.qwen.ai/",
    },
    "xiaomimo-web": {
        "name": "XiaoMiMo Web",
        "base_url": "https://www.xiaomimo.com",
        "default_model": "xiaomimo-chat",
        "context_window": 32000,
        "max_tokens": 8192,
        "cost": {"input": 0, "output": 0, "cacheRead": 0, "cacheWrite": 0},
        "description": "XiaoMiMo through www.xiaomimo.com (browser session)",
        "auth_url": "https://www.xiaomimo.com/",
    },
}
